codecov:
  branch: master

coverage:
  precision: 2
  round: down
  range: "0...100" # 70...100

  status:
    project: true
    patch: true
    changes: false

  ignore:
    - "build/**/*"
    - "src/tests/**/*"
    - "src/*/tests/*"
    - "src/*/tests/**/*"
    - "src/e2e/**/*"
    - "src/gui-qml/**/*"
    - "src/*/vendor/*"
    - "src/*/vendor/**/*"

component_management:
  individual_components:
    - component_id: cli
      name: CLI
      paths:
        - src/cli/*
    - component_id: crash_reporter
      name: Crash Reporter
      paths:
        - src/crash-reporter/*
    - component_id: gui
      name: GUI
      paths:
        - src/gui/*
    - component_id: lib
      name: Library
      paths:
        - src/lib/*
    - component_id: sources
      name: Sources
      paths:
        - src/sites/*

comment:
  layout: "header, diff"
  behavior: default
